### ISSUE TITLE
Cannot find config file - Issue 

### ISSUE THREAD

**Issue by wuvvie** [MinecraftBA/MC-Unique-Commands#1]
Could not find 'uniquecommands-server.toml' for permission setup 

running /config showfile unifiedstorage SERVER (+ common and client) returns as not found

![Annotation 2023-12-31 004352](https://github.com/MinecraftBA/MC-Unique-Commands/assets/143292561/8a9ad68e-56b0-439f-8ac0-0e3b28fe3757)

**Comment by wuvvie** [comment]
my bad had a copy paste of another 'u' titled mod, the command was /config showfile uniquecommands SERVER (+ common and client)

**Comment by MinecraftBA** [comment]
@wuvvie Thanks for reporting anyway, glad it's working.
Closing this issue now. :)

**Comment by wuvvie** [comment]
Oh, the comment was just amending a typo I made in the original post. The issue is still present; there is no config file for unique commands.

**Comment by MinecraftBA** [comment]
@wuvvie Can you please specify which version of the mod are you using?

The config file should be available at this location:
saves\\{your_world_name}\serverconfig\uniquecommands-server.toml

**Comment by MinecraftBA** [comment]
@wuvvie  Even when we type command that you've sent, it's displaying properly:

![image](https://github.com/MinecraftBA/MC-Unique-Commands/assets/126400629/91a6c5ac-6534-4b04-9a7e-0cbe923800a1)

Make sure that you use latest version 1.0.0 for MC 1.20.4.

If you need 1.0.0 version for older MC release, let us know and we will try to work it out.

**Comment by wuvvie** [comment]
apologies for the delay in response ^^; (and happy holidays!)

I am on 1.20.2-0.4.0 (working on a 1.20.2 modpack)

**Comment by MinecraftBA** [comment]
@wuvvie  We have just released support version for 1.20.2:
[https://legacy.curseforge.com/minecraft/mc-mods/unique-commands/files/5019624](https://legacy.curseforge.com/minecraft/mc-mods/unique-commands/files/5019624)

Let us know if it works for you :)

**Comment by wuvvie** [comment]
thank you for releasing a fix! 
It works and the config file is present. Cheers! ^^
